source 'https://github.com/CocoaPods/Specs.git'
platform :osx, "10.13"

target 'Recipe Robot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recipe Robot
  pod 'Sparkle'

  target 'Recipe RobotTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
