#!/usr/bin/python

# List of sample data sets used to test Recipe Robot with various apps.
SAMPLE_DATA = [
    {
        # Inception
        "bundle_id": "com.elliotjordan.recipe-robot",
        "developer": "Elliot Jordan",
        "input_path": "https://github.com/homebysix/recipe-robot",
        "app_name": "Recipe Robot",
    },
    {
        "bundle_id": "com.apple.ScriptEditor.id.Open-in-Atom",
        "developer": "Chris Dzombak",
        "input_path": "https://github.com/cdzombak/finder-atom",
        "app_name": "Open in Atom",
    },
    {
        "bundle_id": "com.hjuutilainen.MunkiAdmin",
        "developer": "Hannes Juutilainen",
        "input_path": "https://github.com/hjuutilainen/munkiadmin",
        "app_name": "MunkiAdmin",
    },
    {
        # Bitbucket URL
        "app_name": "MDS",
        "developer": "Twocanoes Software",
        "input_path": "https://bitbucket.org/twocanoes/macdeploystick",
        "bundle_id": "com.twocanoes.MacDeployStick",
    },
    {
        # Devmate URL
        "app_name": "Waltr",
        "developer": "Dmytro Makukha",
        "input_path": "https://dl.devmate.com/com.softorino.Waltr/WALTR.dmg",
        "bundle_id": "com.softorino.Waltr",
    },
    {
        # Download URL w/ bad Sparkle feed
        "app_name": "Adapter",
        "developer": "Macroplant",
        "input_path": "http://www.macroplant.com/latest-binaries/adapter-mac.dmg",
        "bundle_id": "com.macroplant.adapter",
    },
    {
        # Download URL, prefpane bundle
        "app_name": "HyperDock",
        "developer": "Christian  Baumgart",
        "input_path": "https://bahoom.com/hyperdock/download",
        "bundle_id": "de.bahoom.HyperDock.prefpane",
    },
    {
        # Download URL, app in dmg
        "app_name": "Chat",
        "developer": "Google",
        "input_path": "https://dl.google.com/chat/latest/InstallHangoutsChat.dmg",
        "bundle_id": "com.google.chat",
    },
    {
        # Path to app with Sparkle feed
        "app_name": "AutoPkgr",
        "developer": "The Linde Group Computer Support",
        "input_path": "/Applications/AutoPkgr.app",  # Requires app to be installed.
        "bundle_id": "com.lindegroup.AutoPkgr",
    },
    {
        # Sparkle feed for app
        "app_name": "AutoPkgr",
        "developer": "The Linde Group Computer Support",
        "input_path": "https://raw.githubusercontent.com/lindegroup/autopkgr/appcast/appcast.xml",
        "bundle_id": "com.lindegroup.AutoPkgr",
    },
    {
        # GitHub URL
        "app_name": "MunkiAdmin",
        "developer": "Hannes Juutilainen",
        "input_path": "https://github.com/hjuutilainen/munkiadmin",
        "bundle_id": "com.hjuutilainen.MunkiAdmin",
    },
    {
        # Download URL to app in pkg
        "app_name": "Kindle Previewer 3",
        "developer": "AMZN Mobile",
        "input_path": "https://s3.amazonaws.com/kindlepreviewer3/KindlePreviewerInstaller.pkg",
        "bundle_id": "com.amazon.kpr",
    },
    {
        # Download URL to pkg in dmg
        "app_name": "Karabiner",
        "developer": "Fumihiko Takayama",
        "input_path": "https://pqrs.org/osx/karabiner/files/Karabiner-10.9.0.dmg",
        "bundle_id": "org.pqrs.Karabiner",
    },
    {
        # SourceForge URL
        "app_name": "GrandPerspective",
        "developer": "Erwin Bonsma",
        "input_path": "http://grandperspectiv.sourceforge.net",
        "bundle_id": "net.sourceforge.grandperspectiv",
    },
    {
        # Zipped, mutliple apps not on root level
        "app_name": "cd to",
        "developer": "James Tuley",
        "input_path": "https://github.com/jbtule/cdto",
        "bundle_id": "name.tuley.jay.cdto",
    },
    {
        # Download URL to app in zip
        "app_name": "PowerPhotos",
        "developer": "Fat Cat Software",
        "input_path": "https://www.fatcatsoftware.com/powerphotos/PowerPhotos.zip",
        "bundle_id": "com.fatcatsoftware.PowerPhotos",
    },
    {
        # GitHub URL to qlgenerator bundle
        "app_name": "Provisioning",
        "developer": "Craig Hockenberry",
        "input_path": "https://github.com/chockenberry/Provisioning",
        "bundle_id": "com.iconfactory.Provisioning",
    },
    {
        # Path to app with Sparkle feed, zip download
        "app_name": "Evernote",
        "developer": "Evernote",
        "input_path": "/Applications/Evernote.app",  # Requires app to be installed.
        "bundle_id": "com.evernote.Evernote",
    },
    {
        # Sparkle feed, app in zip
        "app_name": "Evernote",
        "developer": "Evernote",
        "input_path": "https://update.evernote.com/public/ENMacSMD/EvernoteMacUpdate.xml",
        "bundle_id": "com.evernote.Evernote",
    },
    {
        # Sparkle feed, app in zip
        "app_name": "foo",
        "developer": "foo",
        "input_path": "foo",
        "bundle_id": "foo",
    },
    # Other collected test cases...
    {
        "bundle_id": "net.istumbler",
        "input_path": "https://istumbler.net/feeds/appcast.rss",
        "app_name": "iStumbler",
        "developer": "Alf Watt",
    },
    {
        "bundle_id": "ctrlla.Polymail",
        "input_path": "https://sparkle-updater.polymail.io/cast.xml",
        "app_name": "Polymail",
        "developer": "CTRL LA",
    },
    {
        "bundle_id": "com.grammarly.DesktopEditor",
        "input_path": "https://download-editor.grammarly.com/osx/Grammarly.dmg",
        "app_name": "Grammarly",
        "developer": "Grammarly",
    },
    {
        "bundle_id": "uk.co.insili.Code-Cookbook-for-Swift",
        "input_path": "https://s3.amazonaws.com/iswift/codecookbook.xml",
        "app_name": "Code Cookbook for Swift",
        "developer": "Ioannis Zafeiropoulos",
    },
    {
        "bundle_id": "com.nateparrott.Flashlight",
        "input_path": "https://raw.githubusercontent.com/nate-parrott/flashlight/master/Appcast.xml",
        "app_name": "Flashlight",
        "developer": "James Parrott",
    },
    {
        "bundle_id": "com.fournova.Tower3",
        "input_path": "https://www.git-tower.com/download",
        "app_name": "Tower",
        "developer": "fournova Software",
    },
    {
        "bundle_id": "com.devon-technologies.think2",
        "input_path": "http://www.devon-technologies.com/Sparkle/DEVONthink2.xml",
        "app_name": "DEVONthink",
        "developer": "DEVONtechnologies",
    },
    {
        "bundle_id": "com.riffsy.GIF-for-Mac",
        "input_path": "https://media.tenor.co/mac/gif_for_mac_appcast.xml",
        "app_name": "Tenor GIF Keyboard for Mac",
        "developer": "Tenor",
    },
    {
        "bundle_id": "com.codeius.izip",
        "input_path": "https://www.izip.com/updates",
        "app_name": "iZip",
        "developer": "iBoostUp",
    },
    {
        "bundle_id": "com.riot.Anvil",
        "input_path": "https://sparkler.herokuapp.com/apps/3/updates.xml",
        "app_name": "Anvil",
        "developer": "S Schofield",
    },
    {
        "bundle_id": "com.xrite.pantonecolormanager",
        "input_path": "https://pcm.pantone.com/pantonecolormanager/mac/feed/pcm_feed.xml",
        "app_name": "PANTONE Color Manager",
        "developer": "X-Rite",
    },
    {
        "bundle_id": "com.mouapp.Mou",
        "input_path": "http://mouapp.com/up/updates.xml",
        "app_name": "Mou",
        "developer": "Chen Luo",
    },
    {
        "bundle_id": "com.koingosw.DisplayMaestro",
        "input_path": "https://www.koingosw.com/products/getmirrorfile.php?path=%2Fproducts%2Fdisplaymaestro%2Fdownload%2Fdisplaymaestro.dmg",
        "app_name": "Display Maestro",
        "developer": "Koingo Software",
    },
    {
        "bundle_id": "net.brockerhoff.RB.RB-App-Checker-Lite",
        "input_path": "https://brockerhoff.net/RB/AppCheckerLite/RBACL.zip",
        "app_name": "RB App Checker Lite",
        "developer": "Rainer Brockerhoff",
    },
    {
        "bundle_id": "com.manytricks.Name Mangler",
        "input_path": "https://manytricks.com/namemangler/appcast.xml",
        "app_name": "Name Mangler",
        "developer": "Mangler",
    },
    {
        "bundle_id": "com.dmitrynikolaev.numi",
        "input_path": "https://updates.devmate.com/com.dmitrynikolaev.numi.xml",
        "app_name": "Numi",
        "developer": "DMITRY NIKOLAEV",
    },
    {
        "bundle_id": "org.eyebeam.SelfControl",
        "input_path": "https://selfcontrolapp.com/SelfControlAppcast.xml",
        "app_name": "SelfControl",
        "developer": "Charlie Stigler",
    },
    {
        "bundle_id": "com.RichSomerfield.TextBar",
        "input_path": "https://raw.githubusercontent.com/richie5um/richie5um.github.io/master/apps/textbar/sparkle_textbar.xml",
        "app_name": "TextBar",
        "developer": "Rich Somerfield",
    },
    {
        "bundle_id": "com.irradiatedsoftware.Tickets",
        "input_path": "https://www.irradiatedsoftware.com/updates/profiles/tickets.php",
        "app_name": "Tickets",
        "developer": "Irradiated Software",
    },
    {
        "bundle_id": "com.irradiatedsoftware.SwitchUp",
        "input_path": "https://www.irradiatedsoftware.com/updates/profiles/switchup.php",
        "app_name": "SwitchUp",
        "developer": "Irradiated Software",
    },
    {
        "bundle_id": "com.resilio.Sync",
        "input_path": "https://download-cdn.getsync.com/stable/osx/Resilio-Sync.dmg",
        "app_name": "Resilio Sync",
        "developer": "Resilio",
    },
    {
        "bundle_id": "com.naarak.Scherlokk",
        "input_path": "https://naarakstudio.com/download/Scherlokk.dmg",
        "app_name": "Scherlokk",
        "developer": "Grzegorz Staszczyk",
    },
    {
        "bundle_id": "net.publicspace.dist.noisemachine",
        "input_path": "http://www.publicspace.net/app/nm.xml",
        "app_name": "Noise Machine",
        "developer": "Frank Reiff",
    },
    {
        "bundle_id": "ee.clockwise.gmask",
        "input_path": "http://gmask.clockwise.ee/check_update/",
        "app_name": "Gas Mask",
        "developer": "Mask",
    },
    {
        "bundle_id": "com.markdouma.FontFinagler",
        "input_path": "http://www.markdouma.com/fontfinagler/version.xml",
        "app_name": "Font Finagler",
        "developer": "Finagler",
    },
    {
        "bundle_id": "com.nothingmagical.whiskey",
        "input_path": "http://usewhiskey.com/latest",
        "app_name": "Whiskey",
        "developer": "Sam Soffes",
    },
    {
        "bundle_id": "com.smallerapp.Smaller",
        "input_path": "http://25.io/smaller/up/updates.xml",
        "app_name": "Smaller",
        "developer": "Chen Luo",
    },
    {
        "bundle_id": "com.enolsoft.powerunarchiver",
        "input_path": "https://www.cisdem.com/download/cisdem-betterunarchiver.dmg",
        "app_name": "Cisdem BetterUnarchiver",
        "developer": "Enolsoft",
    },
    {
        "bundle_id": "com.helftone.monodraw",
        "input_path": "https://updates.helftone.com/monodraw/appcast-beta.xml",
        "app_name": "Monodraw",
        "developer": "Helftone",
    },
    {
        "bundle_id": "com.koingosw.appbolish",
        "input_path": "https://www.koingosw.com/products/getmirrorfile.php?path=%2Fproducts%2Fappbolish%2Fdownload%2Fappbolish.dmg",
        "app_name": "AppBolish",
        "developer": "Koingo Software",
    },
    {
        "bundle_id": "com.DigiDNA.iMazingMac",
        "input_path": "https://updates.devmate.com/com.DigiDNA.iMazingMac.xml",
        "app_name": "iMazing",
        "developer": "DigiDNA",
    },
    {
        "bundle_id": "com.activecollab.activecollab-desktop",
        "input_path": "https://accounts.activecollab.com/api/v2/desktop-apps/activecollab/releases/darwin/download",
        "app_name": "ActiveCollab",
        "developer": "A51 D.O.O.",
    },
    {
        "bundle_id": "com.SugarSync.SugarSync",
        "input_path": "https://www.sugarsync.com/downloads/InstallSugarSync.dmg",
        "app_name": "SugarSync",
        "developer": "SugarSync",
    },
    {
        "bundle_id": "com.kite.Kite",
        "input_path": "https://release.kite.com/appcast.xml",
        "app_name": "Kite",
        "developer": "MANHATTAN ENGINEERING",
    },
    {
        "bundle_id": "com.yellowmug.FolderBrander",
        "input_path": "https://www.yellowmug.com/download/FolderBrander.dmg",
        "app_name": "FolderBrander",
        "developer": "Jay Teo",
    },
    {
        "bundle_id": "com.brettterpstra.marked2",
        "input_path": "https://updates.marked2app.com/marked.xml",
        "app_name": "Marked 2",
        "developer": "Brett Terpstra",
    },
    {
        "bundle_id": "com.smartmontools.pkg",
        "app_name": "S.M.A.R.T. Monitoring Tools",
        "developer": "Tools",
        "input_path": "https://sourceforge.net/projects/smartmontools/",
    },
    {
        "bundle_id": "com.blackpixel.netnewswire",
        "input_path": "https://updates.blackpixel.com/updates?app=nnw",
        "app_name": "NetNewsWire",
        "developer": "Black Pixel",
    },
    {
        "bundle_id": "com.manytricks.Open-With Manager",
        "input_path": "https://manytricks.com/download/openwithmanager",
        "app_name": "Open-With Manager",
        "developer": "Manager",
    },
    {
        "bundle_id": "com.rogueamoeba.Piezo",
        "input_path": "https://d2oxtzozd38ts8.cloudfront.net/piezo/download/Piezo.zip",
        "app_name": "Piezo",
        "developer": "Rogue Amoeba Software",
    },
    {
        "bundle_id": "com.supermegaultragroovy.tapedeck",
        "input_path": "http://tapedeckapp.com/download/appcast-1.0.xml",
        "app_name": "TapeDeck",
        "developer": "SuperMegaUltraGroovy",
    },
    {
        "bundle_id": "com.manytricks.Keymo",
        "input_path": "https://manytricks.com/keymou/appcast/?version=1",
        "app_name": "Keymo",
        "developer": "Keymo",
    },
    {
        "bundle_id": "com.houdah.HoudahSpot",
        "input_path": "https://www.houdah.com/houdahSpot/updates/cast4.xml",
        "app_name": "HoudahSpot",
        "developer": "Houdah Software",
    },
    {
        "bundle_id": "com.blacey.SuperDuper!",
        "input_path": "https://s3.amazonaws.com/shirtpocket/SuperDuper/SuperDuper!.dmg",
        "app_name": "SuperDuper",
        "developer": "Bruce Lacey",
    },
    {
        "bundle_id": "com.appzapper.AppZapper",
        "input_path": "https://www.appzapper.com/az2appcast.xml",
        "app_name": "AppZapper",
        "developer": "AppZapper",
    },
    {
        "bundle_id": "com.evernote.Evernote",
        "input_path": "https://update.evernote.com/public/ENMacSMD/EvernoteMacUpdate.xml",
        "app_name": "Evernote",
        "developer": "Evernote",
    },
    {
        "bundle_id": "com.cocmoc.appreviews",
        "app_name": "App Reviews",
        "developer": "Knut Inge Grosland",
        "input_path": "https://github.com/knutigro/AppReviews",
    },
    {
        "bundle_id": "com.potionfactory.TheHitList",
        "input_path": "https://launch.karelia.com/appcast.php?product=9&amp;appname=The+Hit+List",
        "app_name": "The Hit List",
        "developer": "Karelia Software",
    },
    {
        "bundle_id": "com.literatureandlatte.scrivener3",
        "input_path": "https://www.literatureandlatte.com/downloads/scrivener-3.xml",
        "app_name": "Scrivener",
        "developer": "Literature & Latte",
    },
    {
        "bundle_id": "com.globaldelight.Boom2",
        "input_path": "https://updates.devmate.com/com.globaldelight.Boom2.xml",
        "app_name": "Boom 2",
        "developer": "Global Delight Technologies",
    },
    {
        "bundle_id": "com.rogueamoeba.Fission",
        "input_path": "https://d2oxtzozd38ts8.cloudfront.net/fission/download/Fission.zip",
        "app_name": "Fission",
        "developer": "Rogue Amoeba Software",
    },
    {
        "bundle_id": "com.fatcatsoftware.PowerPhotos",
        "input_path": "https://www.fatcatsoftware.com/powerphotos/PowerPhotos.zip",
        "app_name": "PowerPhotos",
        "developer": "Fat Cat Software",
    },
    {
        "bundle_id": "com.iconfactory.xScope",
        "input_path": "https://iconfactory.com/appcasts/xScope/appcast.xml",
        "app_name": "xScope",
        "developer": "The Iconfactory",
    },
    {
        "bundle_id": "com.uglyapps.HocusFocus",
        "input_path": "https://hocusfoc.us/updates.xml",
        "app_name": "Hocus Focus",
        "developer": "Nial Giacomelli",
    },
    {
        "bundle_id": "com.marklyapp.RightFont",
        "input_path": "https://rightfontapp.com/update/appcast.xml",
        "app_name": "RightFont",
        "developer": "LIYI CHENG",
    },
    {
        "bundle_id": "com.soma-zone.BackupLoupe",
        "input_path": "https://somazonecom.ipage.com/soma-zone.com/BackupLoupe/a/appcast_update.xml",
        "app_name": "BackupLoupe",
        "developer": "Robby Pahlig",
    },
    {
        "bundle_id": "com.soma-zone.LaunchControl",
        "input_path": "https://somazonecom.ipage.com/soma-zone.com/LaunchControl/a/appcast_update.xml",
        "app_name": "LaunchControl",
        "developer": "Robby Pahlig",
    },
    {
        "bundle_id": "com.clickablebliss.ProfitTrain",
        "input_path": "https://razorant.com/profittrain/profileInfo",
        "app_name": "ProfitTrain",
        "developer": "ProfitTrain",
    },
    {
        "bundle_id": "net.projectwizards.merlinproject",
        "input_path": "https://www.projectwizards.net/downloads/MerlinProject.zip",
        "app_name": "Merlin Project",
        "developer": "ProjectWizards",
    },
    {
        "bundle_id": "com.fuekiin.NightOwl",
        "input_path": "https://nightowl.kramser.xyz/files/NightOwl.dmg",
        "app_name": "NightOwl",
        "developer": "Benjamin Kramser",
    },
    {
        "bundle_id": "com.bluemangolearningsystems.clarify-osx",
        "input_path": "http://files.clarify-it.com/v2/updaters/release/appcast.xml",
        "app_name": "Clarify",
        "developer": "Blue Mango Learning Systems",
    },
    {
        "bundle_id": "com.supermegaultragroovy.capo3.mac",
        "input_path": "http://capoapp.com/download.php?v=latest",
        "app_name": "Capo",
        "developer": "SuperMegaUltraGroovy",
    },
    {
        "bundle_id": "com.tunabelly.handsfree2",
        "input_path": "https://www.tunabellysoftware.com/resources/sparkle/handsfree2.xml",
        "app_name": "HandsFree 2",
        "developer": "Tunabelly Software",
    },
    {
        "bundle_id": "com.koingosw.LibrarianPro",
        "input_path": "https://www.koingosw.com/products/getmirrorfile.php?path=%2Fproducts%2Flibrarianpro%2Fdownload%2Flibrarianpro.dmg",
        "app_name": "Librarian Pro",
        "developer": "Koingo Software",
    },
    {
        "bundle_id": "com.flinto.Flinto",
        "input_path": "https://www.flinto.com/download_latest",
        "app_name": "Flinto",
        "developer": "Flinto",
    },
    {
        "bundle_id": "com.edhsw.miXscope",
        "input_path": "http://www.edhsw.com/mixscope/miXscope.dmg",
        "app_name": "miXscope",
        "developer": "miXscope",
    },
    {
        "bundle_id": "com.bartelsmedia.ShareMouse",
        "input_path": "http://www.keyboard-and-mouse-sharing.com/ShareMouseSetup.dmg",
        "app_name": "ShareMouse",
        "developer": "Bartels Media",
    },
    {
        "bundle_id": "com.yellowmug.EasyFrame",
        "input_path": "https://www.yellowmug.com/download/EasyFrame.dmg",
        "app_name": "EasyFrame",
        "developer": "Jay Teo",
    },
    {
        "bundle_id": "com.koingosw.ProjectCanvas",
        "input_path": "https://www.koingosw.com/products/getmirrorfile.php?path=%2Fproducts%2Fprojectcanvas%2Fdownload%2Fprojectcanvas.dmg",
        "app_name": "Project Canvas",
        "developer": "Koingo Software",
    },
    {
        "bundle_id": "com.mymixapps.FilePane",
        "input_path": "https://updates.devmate.com/com.mymixapps.FilePane.xml",
        "app_name": "FilePane",
        "developer": "Sergii Iamkovyi",
    },
    {
        "bundle_id": "uk.co.insili.iSwift",
        "input_path": "https://s3.amazonaws.com/iswift/iswift.xml",
        "app_name": "iSwift",
        "developer": "Ioannis Zafeiropoulos",
    },
    {
        "bundle_id": "com.gngrwzrd.paddle.BetterWindowManager",
        "input_path": "https://www.gngrwzrd.com/betterwindowmanager-appcast.xml",
        "app_name": "Better Window Manager",
        "developer": "Aaron Smith",
    },
    {
        "bundle_id": "com.foldingtext.paddle.FoldingText",
        "input_path": "https://s3.amazonaws.com/foldingtext/FoldingText.dmg",
        "app_name": "FoldingText",
        "developer": "Jesse Grosjean",
    },
    {
        "bundle_id": "com.tunabellysoftware.silentstart",
        "input_path": "https://www.tunabellysoftware.com/resources/sparkle/silentstart.xml",
        "app_name": "Silent Start",
        "developer": "Tunabelly Software",
    },
    {
        "bundle_id": "com.toggl.toggldesktop.TogglDesktop",
        "input_path": "https://assets.toggl.com/installers/darwin_stable_appcast.xml",
        "app_name": "TogglDesktop",
        "developer": "Apprise",
    },
    {
        "bundle_id": "com.koingosw.DigitalSentry",
        "input_path": "https://www.koingosw.com/products/getmirrorfile.php?path=%2Fproducts%2Fdigitalsentry%2Fdownload%2Fdigitalsentry.dmg",
        "app_name": "Digital Sentry",
        "developer": "Koingo Software",
    },
    {
        "bundle_id": "com.devon-technologies.agent",
        "input_path": "http://www.devon-technologies.com/Sparkle/DEVONagent.xml",
        "app_name": "DEVONagent",
        "developer": "DEVONtechnologies",
    },
    {
        "bundle_id": "com.bitbq.Changes",
        "input_path": "https://bitbq_changes.s3.amazonaws.com/changes-production.xml",
        "app_name": "Changes",
        "developer": "BitBQ",
    },
    {
        "bundle_id": "com.rogueamoeba.Airfoil",
        "input_path": "https://d2oxtzozd38ts8.cloudfront.net/airfoil/download/Airfoil.zip",
        "app_name": "Airfoil",
        "developer": "Rogue Amoeba Software",
    },
    {
        "bundle_id": "com.soma-zone.Ammonite",
        "input_path": "https://somazonecom.ipage.com/soma-zone.com/Ammonite/a/appcast.xml",
        "app_name": "Ammonite",
        "developer": "Robby Pahlig",
    },
    {
        "bundle_id": "com.macpaw.CleanMyMac2",
        "input_path": "https://updates.devmate.com/com.macpaw.CleanMyMac2.xml",
        "app_name": "CleanMyMac 2",
        "developer": "MacPaw",
    },
    {
        "bundle_id": "com.devon-technologies.thinkpro2",
        "input_path": "http://www.devon-technologies.com/Sparkle/DEVONthinkPro2.xml",
        "app_name": "DEVONthink Pro",
        "developer": "DEVONtechnologies",
    },
    {
        "bundle_id": "com.metabase.Metabase",
        "input_path": "https://s3.amazonaws.com/downloads.metabase.com/appcast.xml",
        "app_name": "Metabase",
        "developer": "Metabase",
    },
    {
        "bundle_id": "com.coppertino.Vox",
        "input_path": "https://updates.devmate.com/com.coppertino.Vox.xml",
        "app_name": "Vox",
        "developer": "Coppertino",
    },
    {
        "bundle_id": "BradJasper.focus",
        "input_path": "https://heyfocus.com/appcast.xml",
        "app_name": "Focus",
        "developer": "Bradley Jasper",
    },
    {
        "bundle_id": "de.bahoom.HyperDock.prefpane",
        "input_path": "https://bahoom.com/hyperdock/download",
        "app_name": "HyperDock",
        "developer": "Christian  Baumgart",
    },
    {
        "bundle_id": "com.brettterpstra.stretchlink",
        "input_path": "http://abyss.designheresy.com/stretchlink/stretchlink.xml",
        "app_name": "StretchLink",
        "developer": "Brett Terpstra",
    },
    {
        "bundle_id": "net.sourceforge.skim-app.skim",
        "input_path": "https://skim-app.sourceforge.io/skim.xml",
        "app_name": "Skim",
        "developer": "Skim",
    },
    {
        "bundle_id": "com.perma.chat",
        "input_path": "https://updates.devmate.com/com.perma.chat.xml",
        "app_name": "Chat",
        "developer": "Christian Owens",
    },
    {
        "bundle_id": "com.fatcatsoftware.pledpro",
        "input_path": "https://www.fatcatsoftware.com/plisteditpro/PlistEditPro.zip",
        "app_name": "PlistEdit Pro",
        "developer": "Fat Cat Software",
    },
    {
        "bundle_id": "com.manytricks.Displaperture",
        "input_path": "https://manytricks.com/download/displaperture",
        "app_name": "Displaperture",
        "developer": "Many Tricks",
    },
    {
        "bundle_id": "com.yellowmug.FileChute",
        "input_path": "http://yellowmug.com/filechute/appcast-1011.xml",
        "app_name": "FileChute",
        "developer": "Jay Teo",
    },
    {
        "bundle_id": "de.appgineers.Mountain",
        "input_path": "https://appgineers.de/mountain/files/mountaincast.xml",
        "app_name": "Mountain",
        "developer": "Jan Linxweiler",
    },
    {
        "bundle_id": "com.yellowmug.YemuZip",
        "input_path": "http://yellowmug.com/yemuzip/appcast.xml",
        "app_name": "YemuZip",
        "developer": "Jay Teo",
    },
    {
        "bundle_id": "net.brockerhoff.RB.RB-App-Quarantine",
        "input_path": "https://brockerhoff.net/RB/AppQuarantine/RBAQ.zip",
        "app_name": "RB App Quarantine",
        "developer": "Rainer Brockerhoff",
    },
    {
        "bundle_id": "com.manytricks.TimeSink",
        "input_path": "https://manytricks.com/timesink/appcast.xml",
        "app_name": "Time Sink",
        "developer": "Sink",
    },
    {
        "bundle_id": "com.hjuutilainen.MunkiAdmin",
        "app_name": "MunkiAdmin",
        "developer": "Hannes Juutilainen",
        "input_path": "https://github.com/hjuutilainen/munkiadmin/releases",
    },
    {
        "bundle_id": "com.yellowmug.SizzlingKeys",
        "input_path": "https://www.yellowmug.com/download/SizzlingKeys.dmg",
        "app_name": "SizzlingKeys",
        "developer": "Jay Teo",
    },
    {
        "bundle_id": "com.manytricks.DesktopCurtain",
        "input_path": "https://manytricks.com/desktopcurtain/appcast.xml",
        "app_name": "Desktop Curtain",
        "developer": "Curtain",
    },
    {
        "bundle_id": "com.github.IngmarStein.Monolingual",
        "input_path": "https://ingmarstein.github.io/Monolingual/appcast.xml",
        "app_name": "Monolingual",
        "developer": "Ingmar Stein",
    },
    {
        "bundle_id": "com.binarynights.ForkLift-3",
        "input_path": "https://updates.binarynights.com/ForkLift3/update.xml",
        "app_name": "ForkLift",
        "developer": "BinaryNights",
    },
    {
        "bundle_id": "co.warewolf.Espresso",
        "input_path": "https://espressoapp.com/updates/appcast.xml",
        "app_name": "Espresso",
        "developer": "Warewolf",
    },
    {
        "bundle_id": "co.ysberg.Folio",
        "input_path": "https://s3.amazonaws.com/folioformac.com/folioupdates.xml.rss",
        "app_name": "Folio",
        "developer": "Hanno ter Hoor",
    },
    {
        "bundle_id": "fi.lacquer.Radi",
        "input_path": "https://radiapp.com/Radi.zip",
        "app_name": "Radi",
        "developer": "Lacquer",
    },
    {
        "bundle_id": "com.charlessoft.CocoaTads",
        "input_path": "https://www.charlessoft.com/CocoaTADS.zip",
        "app_name": "CocoaTADS",
        "developer": "CocoaTADS",
    },
    {
        "bundle_id": "com.charlessoft.nibunlocker",
        "input_path": "https://www.charlessoft.com/NibUnlocker.zip",
        "app_name": "NibUnlocker",
        "developer": "NibUnlocker",
    },
    {
        "bundle_id": "com.tableausoftware.tableaureader",
        "input_path": "https://www.tableau.com/downloads/reader/mac",
        "app_name": "Tableau Reader",
        "developer": "Tableau Software",
    },
    {
        "bundle_id": "com.houdah.Tembo2",
        "input_path": "https://www.houdah.com/tembo/updates/cast2.xml",
        "app_name": "Tembo",
        "developer": "Houdah Software",
    },
    {
        "bundle_id": "com.manytricks.Leech",
        "input_path": "https://manytricks.com/leech/appcast.xml",
        "app_name": "Leech",
        "developer": "Leech",
    },
    {
        "bundle_id": "com.quip.Desktop",
        "input_path": "https://quip-clients.com/macosx_5.4.47.dmg",
        "app_name": "Quip",
        "developer": "Quip",
    },
    {
        "bundle_id": "com.jamapi.fontnuke",
        "input_path": "https://www.jamapi.com/fontnuke/fontnuke-update-appcast.xml",
        "app_name": "FontNuke",
        "developer": "FontNuke",
    },
    {
        "bundle_id": "com.koingosw.RoboPostman",
        "input_path": "https://www.koingosw.com/products/getmirrorfile.php?path=%2Fproducts%2Frobopostman%2Fdownload%2Frobopostman.dmg",
        "app_name": "RoboPostman",
        "developer": "Koingo Software",
    },
    {
        "bundle_id": "com.karelia.Sandvox",
        "input_path": "https://www.karelia.com/files/8/Sandvox.zip",
        "app_name": "Sandvox",
        "developer": "Karelia Software",
    },
    {
        "bundle_id": "com.gravityapps.Tags",
        "input_path": "http://www.caseapps.com/downloads/updates/tags/tags2-update.xml",
        "app_name": "Tags",
        "developer": "Tags",
    },
    {
        "bundle_id": "com.softorino.Waltr",
        "input_path": "https://updates.devmate.com/com.softorino.Waltr.xml",
        "app_name": "Waltr",
        "developer": "Dmytro Makukha",
    },
    {
        "bundle_id": "com.googlecode.iterm2",
        "input_path": "https://iterm2.com/appcasts/final.xml",
        "app_name": "iTerm2",
        "developer": ["GEORGE NACHMAN"],
    },
    {
        "bundle_id": "com.xilinus.MockSmtp",
        "input_path": "http://www.mocksmtpapp.com/MockSmtp.zip",
        "app_name": "MockSmtp",
        "developer": "MockSmtp",
    },
    {
        "bundle_id": "com.twocanoes.MacDeployStick",
        "input_path": "https://www.twocanoes.com/macdeploystick/updates/macdeploystick-software-updates.xml",
        "app_name": "MDS",
        "developer": "Twocanoes Software, Inc.",
    },
    {
        "bundle_id": "com.rogueamoeba.Nicecast",
        "input_path": "https://d2oxtzozd38ts8.cloudfront.net/nicecast/download/Nicecast.zip",
        "app_name": "Nicecast",
        "developer": "Rogue Amoeba Software",
    },
    {
        "bundle_id": "com.bjango.skalapreview",
        "input_path": "https://download.bjango.com/skalapreview/",
        "app_name": "Skala Preview",
        "developer": "Marc Edwards",
    },
    {
        "bundle_id": "com.ireador.PDFKit",
        "input_path": "https://www.ireador.com/downloads/PDFKit.dmg",
        "app_name": "PDFKit",
        "developer": "Xuepeng Zhang",
    },
    {
        "input_path": "https://yellowmug.com/snapndrag/appcast.xml",
        "app_name": "SnapNDrag",
        "developer": "SnapNDrag",
        "bundle_id": None,
    },
    {
        "bundle_id": "de.dirkwhoffmann.VirtualC64",
        "input_path": "http://dirkwhoffmann.de/virtualc64/VirtualC64Appcast.xml",
        "app_name": "VirtualC64",
        "developer": "VirtualC64",
    },
    {
        "bundle_id": "com.ohanaware.appWrapper3",
        "input_path": "https://www.ohanaware.com/appwrapper/appWrapper3.zip",
        "app_name": "App Wrapper 3",
        "developer": "Ohanaware Co",
    },
    {
        "bundle_id": "com.koingosw.AirRadar",
        "input_path": "https://www.koingosw.com/products/getmirrorfile.php?path=%2Fproducts%2Fairradar%2Fdownload%2Fairradar.dmg",
        "app_name": "AirRadar",
        "developer": "Koingo Software",
    },
    {
        "bundle_id": "com.literatureandlatte.scapple",
        "input_path": "https://www.literatureandlatte.com/downloads/scapple/scapple.xml",
        "app_name": "Scapple",
        "developer": "Literature & Latte",
    },
    {
        "bundle_id": "com.mrrsoftware.NameChanger",
        "input_path": "https://mrrsoftware.com/Downloads/NameChanger/Updates/NameChangerSoftwareUpdates.xml",
        "app_name": "NameChanger",
        "developer": "NameChanger",
    },
    {
        "bundle_id": "com.togo.hotkeyEVE",
        "input_path": "https://s3.amazonaws.com/hotkeyeve/hotkeyEVEappcast.xml",
        "app_name": "EVE",
        "developer": "EVE",
    },
    {
        "input_path": "https://yellowmug.com/easycrop/appcast.xml",
        "app_name": "EasyCrop",
        "developer": "EasyCrop",
        "bundle_id": None,
    },
    {
        "bundle_id": "cc.buechele.Goofy",
        "input_path": "https://raw.githubusercontent.com/danielbuechele/goofy/master/update_feed.xml",
        "app_name": "Goofy",
        "developer": "Daniel Buechele",
    },
    {
        "bundle_id": "ca.brawer.uBar",
        "input_path": "https://brawersoftware.com/appcasts/feeds/ubar/ubar3.xml",
        "app_name": "uBar",
        "developer": "Brawer Canada",
    },
    {
        "bundle_id": "com.bjango.Skala-Color-Installer",
        "input_path": "https://download.bjango.com/skalacolor/",
        "app_name": "Skala Color Installer",
        "developer": "Marc Edwards",
    },
    {
        "bundle_id": "com.tunabellysoftware.cleanmydesktop",
        "input_path": "https://www.tunabellysoftware.com/resources/sparkle/foldertidy.xml",
        "app_name": "Folder Tidy",
        "developer": "Tunabelly Software",
    },
    {
        "bundle_id": "us.freshout.RecordIt",
        "input_path": "https://rink.hockeyapp.net/api/2/apps/5fcda0b48f1dcf0c938b289b9ab57790",
        "app_name": "RecordIt",
        "developer": "Navid Safabakhsh",
    },
    {
        "bundle_id": "com.irradiatedsoftware.iClip",
        "input_path": "https://www.irradiatedsoftware.com/updates/profiles/iclip.php",
        "app_name": "iClip",
        "developer": "Irradiated Software",
    },
    {
        "bundle_id": "com.koingosw.MacPilot",
        "input_path": "https://www.koingosw.com/products/getmirrorfile.php?path=%2Fproducts%2Fmacpilot%2Fdownload%2Fmacpilot.dmg",
        "app_name": "MacPilot",
        "developer": "Koingo Software",
    },
    {
        "bundle_id": "com.clickontyler.VirtualHostX",
        "input_path": "http://shine.clickontyler.com/appcast.php?id=38",
        "app_name": "VirtualHostX",
        "developer": "Tyler Hall",
    },
    {
        "bundle_id": "com.marinersoftware.write",
        "input_path": "https://www.marinersoftware.com/sparkle/MarinerWrite/marinerwrite.xml",
        "app_name": "Mariner Write",
        "developer": "Mariner Software",
    },
    {
        "bundle_id": "com.DanSchimpf.MacJournal",
        "input_path": "https://danschimpf.com/appcasts/MacJournal6.appcast",
        "app_name": "MacJournal",
        "developer": "Mariner Software",
    },
    {
        "bundle_id": "com.lindegroup.AutoPkgr",
        "input_path": "https://raw.githubusercontent.com/lindegroup/autopkgr/appcast/appcast.xml",
        "app_name": "AutoPkgr",
        "developer": "The Linde Group Computer Support Inc",
    },
    {
        "input_path": "https://zoom.us/client/latest/ZoomRooms.pkg",
        "app_name": "ZAAPI",
        "developer": "Zoom Video Communications",
        "bundle_id": None,
    },
    {
        "bundle_id": "com.hegenberg.BetterTouchTool",
        "input_path": "https://updates.bettertouchtool.net/appcast.xml",
        "app_name": "BetterTouchTool",
        "developer": "Andreas Hegenberg",
    },
    {
        "bundle_id": "com.manytricks.Usher",
        "input_path": "https://manytricks.com/usher/appcast.xml",
        "app_name": "Usher",
        "developer": "Usher",
    },
    {
        "bundle_id": "com.devon-technologies.agentexpress",
        "input_path": "http://www.devon-technologies.com/Sparkle/DEVONagentExpress.xml",
        "app_name": "DEVONagent Express",
        "developer": "DEVONtechnologies",
    },
    {
        "bundle_id": "com.tunabellysoftware.tgpro",
        "input_path": "https://www.tunabellysoftware.com/resources/sparkle/tgpro/profileInfo.php",
        "app_name": "TG Pro",
        "developer": "Tunabelly Software",
    },
    {
        "bundle_id": "com.macpaw.CleanMyMac3",
        "input_path": "https://updates.devmate.com/com.macpaw.CleanMyMac3.xml",
        "app_name": "CleanMyMac 3",
        "developer": "MacPaw",
    },
    {
        "input_path": "http://timesoftware.free.fr/timemachineeditor/TimeMachineEditor.pkg",
        "app_name": "TimeMachineEditor",
        "developer": "Thomas CLEMENT",
        "bundle_id": None,
    },
    {
        "bundle_id": "com.plug.Plug2",
        "input_path": "https://www.plugformac.com/updates/plug2/sparklecast.xml",
        "app_name": "Plug",
        "developer": "Alex Marchant",
    },
    {
        "bundle_id": "com.tunabellysoftware.diskdiet",
        "input_path": "https://www.tunabellysoftware.com/resources/sparkle/diskdiet.xml",
        "app_name": "Disk Diet",
        "developer": "Tunabelly Software",
    },
    {
        "bundle_id": "com.potionfactory.Tangerine",
        "input_path": "https://launch.karelia.com/appcast.php?product=13",
        "app_name": "Tangerine!",
        "developer": "Potion Factory",
    },
    {
        "bundle_id": "com.marinersoftware.MacGourmet",
        "input_path": "https://www.marinersoftware.com/sparkle/MacGourmet4/macgourmet4.xml",
        "app_name": "MacGourmet",
        "developer": "Mariner Software",
    },
    {
        "bundle_id": "com.houdah.HoudahGeo",
        "input_path": "https://www.houdah.com/houdahGeo/updates4/cast4.php",
        "app_name": "HoudahGeo",
        "developer": "HoudahGeo",
    },
    {
        "bundle_id": "com.sandstudio.airdroid",
        "input_path": "https://srv3.airdroid.com/p20/web/getbinaryredirect?type=dmg&amp;channel=&amp;version=",
        "app_name": "AirDroid",
        "developer": "Sand Studio",
    },
    {
        "bundle_id": "eu.riverdesign.sparkle",
        "input_path": "https://sparkleapp.com/update/Sparkle.zip",
        "app_name": "Sparkle",
        "developer": "River",
    },
    {
        "bundle_id": "com.qvacua.VimR",
        "input_path": "http://vimr.org/appcast.xml",
        "app_name": "VimR",
        "developer": "Tae Won Ha",
    },
    {
        "bundle_id": "com.maintain.cocktail.elcapitan",
        "input_path": "https://www.maintain.se/downloads/sparkle/elcapitan/elcapitan.xml",
        "app_name": "Cocktail",
        "developer": "Kristofer Szymanski",
    },
    {
        "bundle_id": "com.manytricks.Resolutionator",
        "input_path": "https://manytricks.com/resolutionator/appcast.xml",
        "app_name": "Resolutionator",
        "developer": "Many Tricks",
    },
    {
        "bundle_id": "com.tunnelbear.mac.TunnelBear",
        "input_path": "https://s3.amazonaws.com/tunnelbear/downloads/mac/appcast.xml",
        "app_name": "TunnelBear",
        "developer": "TunnelBear",
    },
    {
        "bundle_id": "com.manytricks.Moom",
        "input_path": "https://manytricks.com/moom/appcast.xml",
        "app_name": "Moom",
        "developer": "Moom",
    },
    {
        "bundle_id": "com.id-design.whatsize",
        "input_path": "https://whatsizemac.com/software/whatsize6/whatsize.dmg",
        "app_name": "WhatSize",
        "developer": "ID-DESIGN",
    },
    {
        "bundle_id": "com.marinersoftware.persona",
        "input_path": "https://www.marinersoftware.com/sparkle/persona/persona.xml",
        "app_name": "Persona",
        "developer": "Mariner Software",
    },
    {
        "bundle_id": "com.koingosw.DataGuardian",
        "input_path": "https://www.koingosw.com/products/getmirrorfile.php?path=%2Fproducts%2Fdataguardian%2Fdownload%2Fdataguardian.dmg",
        "app_name": "Data Guardian",
        "developer": "Koingo Software",
    },
    {
        "bundle_id": "com.manytricks.KeyCodes",
        "input_path": "https://manytricks.com/keycodes/appcast.xml",
        "app_name": "Key Codes",
        "developer": "Codes",
    },
    {
        "bundle_id": "org.derailer.Paparazzi",
        "input_path": "https://derailer.org/paparazzi/appcast/",
        "app_name": "Paparazzi!",
        "developer": "Nate Weaver",
    },
    {
        "bundle_id": "com.pingendo.editor",
        "input_path": "https://github.com/Pingendo/pingendo",
        "app_name": "Pingendo",
        "developer": "Pingendo",
    },
    {
        "bundle_id": "com.macpaw.site.Gemini2",
        "input_path": "https://updates.devmate.com/com.macpaw.site.Gemini2.xml",
        "app_name": "Gemini 2",
        "developer": "MacPaw",
    },
    {
        "bundle_id": "com.devon-technologies.sphereexpress",
        "input_path": "http://www.devon-technologies.com/Sparkle/DEVONsphereExpress.xml",
        "app_name": "DEVONsphere Express",
        "developer": "DEVONtechnologies",
    },
    {
        "bundle_id": "com.flyingmeat.Acorn6",
        "input_path": "https://flyingmeat.com/download/Acorn.zip",
        "app_name": "Acorn",
        "developer": "Flying Meat",
    },
    {
        "bundle_id": "com.macpaw.trial.Hider2",
        "input_path": "https://updates.devmate.com/com.macpaw.site.Hider2.xml",
        "app_name": "Hider 2 Trial",
        "developer": "MacPaw",
    },
    {
        "bundle_id": "com.everythingisgray.TMNotifier",
        "input_path": "https://tmnotifier.com/appcast.xml",
        "app_name": "TMNotifier",
        "developer": "James Barclay",
    },
    {
        "bundle_id": "org.pqrs.Karabiner",
        "input_path": "https://pqrs.org/osx/karabiner/files/appcast.xml",
        "app_name": "Karabiner",
        "developer": "Fumihiko Takayama",
    },
    {
        "bundle_id": "uk.co.opencommunity.vienna2",
        "input_path": "https://viennarss.github.io/sparkle-files/changelog.xml",
        "app_name": "Vienna",
        "developer": "Barijaona Ramaholimihaso",
    },
    {
        "bundle_id": "com.DanPristupov.Fork",
        "input_path": "https://git-fork.com/update/feed.xml",
        "app_name": "Fork",
        "developer": "Danil Pristupov",
    },
    {
        "bundle_id": "com.noodlesoft.Install-Hazel",
        "input_path": "https://www.noodlesoft.com/Products/Hazel/download",
        "app_name": "Install Hazel",
        "developer": "Noodlesoft",
    },
    {
        "bundle_id": "com.gravityapps.SofaControl",
        "input_path": "http://www.caseapps.com/downloads/sofacontrol-update.xml",
        "app_name": "Sofa Control",
        "developer": "Control",
    },
    {
        "bundle_id": "com.koolesache.ColorSnapper2",
        "input_path": "https://s3.amazonaws.com/cs2-appcast/appcast.xml",
        "app_name": "ColorSnapper2",
        "developer": "Alexander Danmayer",
    },
    {
        "bundle_id": "com.contextsformac.Contexts",
        "input_path": "https://contexts.co/appcasts/stable.xml",
        "app_name": "Contexts",
        "developer": "Usman Khalid",
    },
    {
        "bundle_id": "com.macroplant.adapter",
        "input_path": "https://www.macroplant.com/latest-binaries/adapter-mac.dmg",
        "app_name": "Adapter",
        "developer": "Macroplant",
    },
    {
        "bundle_id": "com.koingosw.alarmclockpro",
        "input_path": "https://www.koingosw.com/products/getmirrorfile.php?path=%2Fproducts%2Falarmclockpro%2Fdownload%2Falarmclockpro.dmg",
        "app_name": "Alarm Clock Pro",
        "developer": "Koingo Software",
    },
    {
        "bundle_id": "net.macterm.MacTerm",
        "input_path": "https://www.macterm.net/updates/macterm-latest.dmg",
        "app_name": "MacTerm",
        "developer": "Kevin Grant",
    },
    {
        "bundle_id": "com.sonnysoftware.bookends",
        "input_path": "https://www.sonnysoftware.com/Bookends.dmg",
        "app_name": "Bookends",
        "developer": "Sonny Software",
    },
    {
        "bundle_id": "com.fatcatsoftware.iPhotoLibraryManager",
        "input_path": "https://www.fatcatsoftware.com/iplm/iPhotoLibraryManager.zip",
        "app_name": "iPhoto Library Manager",
        "developer": "Fat Cat Software",
    },
    {
        "bundle_id": "com.install4j.6029-5726-8846-0121.357",
        "input_path": "https://s3.amazonaws.com/wksdownload/Emailchemy-Mac.dmg",
        "app_name": "Emailchemy",
        "developer": "Weird Kid Software",
    },
    {
        "bundle_id": "com.rogueamoeba.audiohijack3",
        "input_path": "https://d2oxtzozd38ts8.cloudfront.net/audiohijack/download/AudioHijack.zip",
        "app_name": "Audio Hijack",
        "developer": "Rogue Amoeba Software",
    },
    {
        "bundle_id": "com.yellowmug.EasyBatchPhoto",
        "input_path": "https://www.yellowmug.com/download/EasyBatchPhoto.dmg",
        "app_name": "EasyBatchPhoto",
        "developer": "Jay Teo",
    },
    {
        "bundle_id": "com.realmacsoftware.deepdreamer",
        "input_path": "https://updates.devmate.com/com.realmacsoftware.deepdreamer.xml",
        "app_name": "Deep Dreamer",
        "developer": "Realmac Software",
    },
    {
        "bundle_id": "com.cisco.experimental.Proximity",
        "input_path": "https://proximity.cisco.com/mac/Proximity.dmg",
        "app_name": "Proximity",
        "developer": "Cisco",
    },
    {
        "bundle_id": "com.martiancraft.Briefs",
        "input_path": "https://giveabrief.s3.amazonaws.com/briefsAppCast.xml",
        "app_name": "Briefs",
        "developer": "Briefs LC",
    },
    {
        "bundle_id": "com.fatcatsoftware.PowerTunes",
        "input_path": "https://www.fatcatsoftware.com/powertunes/PowerTunes.zip",
        "app_name": "PowerTunes",
        "developer": "Fat Cat Software",
    },
    {
        "bundle_id": "com.coconut-flavour.coconutBattery",
        "input_path": "https://coconut-flavour.com/updates/coconutBattery.xml",
        "app_name": "coconutBattery",
        "developer": "Christoph Sinai",
    },
    {
        "bundle_id": "com.charlessoft.TimeTracker",
        "input_path": "https://www.charlessoft.com/TimeTracker.zip",
        "app_name": "TimeTracker",
        "developer": "Charles Srstka",
    },
    {
        "bundle_id": "com.manytricks.Butler",
        "input_path": "https://manytricks.com/butler/butlercast.xml",
        "app_name": "Butler",
        "developer": "Butler",
    },
    {
        "app_name": "ScreenFlow",
        "bundle_id": "net.telestream.screenflow5",
        "developer": "Telestream LLC",
        "input_path": "https://www.telestream.net/updater/screenflow/appcast.xml",
    },
    {
        "app_name": "Station",
        "bundle_id": "org.efounders.BrowserX",
        "developer": "eFounders",
        "input_path": "https://dl.getstation.com/download/osx",
    },
    {
        "app_name": "Docker",
        "bundle_id": "com.docker.docker",
        "developer": "Docker Inc",
        "input_path": "https://download.docker.com/mac/stable/appcast.xml",
    },
    {
        "app_name": "Geekbench 4",
        "bundle_id": "com.primatelabs.Geekbench4",
        "developer": "Primate Labs Inc.",
        "input_path": "https://www.primatelabs.com/appcast/geekbench4.xml",
    },
    {
        "app_name": "Platypus",
        "bundle_id": "org.sveinbjorn.Platypus",
        "developer": "Sveinbjorn Thordarson",
        "input_path": "https://sveinbjorn.org/files/appcasts/PlatypusAppcast.xml",
    },
    {
        "app_name": "Duo Device Health",
        "bundle_id": "com.duosecurity.duo-device-health",
        "developer": "Duo Security, Inc.",
        "input_path": "https://dl.duosecurity.com/DuoDeviceHealth-appcast-macos-latest.xml",
    },
    {
        "app_name": "HyperSwitch",
        "bundle_id": "com.bahoom.HyperSwitch",
        "developer": "Christian  Baumgart",
        "input_path": "https://bahoom.com/hyperswitch/appcast.xml",
    },
    {
        "app_name": "Reflector 3",
        "bundle_id": "com.squirrels.Reflector-2",
        "developer": "Squirrels LLC",
        "input_path": "https://updates.airsquirrels.com/Reflector3/Mac/Reflector3.xml",
    },
    {
        "app_name": "Rocket",
        "bundle_id": "net.matthewpalmer.Rocket",
        "developer": "Matthew Palmer",
        "input_path": "https://dl.devmate.com/net.matthewpalmer.Rocket/Rocket.dmg",
    },
    {
        "app_name": "Airtool",
        "bundle_id": "com.adriangranados.Airtool",
        "developer": "Adrian Granados-Murillo",
        "input_path": "https://www.adriangranados.com/appcasts/airtoolcast.xml",
    },
    {
        "app_name": "Console",
        "bundle_id": "com.xs-labs.Console",
        "developer": "Jean-David Gadina",
        "input_path": "https://github.com/macmade/Console",
    },
    {
        "app_name": "Nomadesk",
        "bundle_id": "com.NomaDesk",
        "developer": "NomaDesk",
        "input_path": "https://secure.nomadesk.com/download/?os=macosx",
    },
    {
        "app_name": "WWDC",
        "bundle_id": "br.com.guilhermerambo.WWDC",
        "developer": "GUILHERME RAMBO",
        "input_path": "https://github.com/insidegui/WWDC/raw/master/Releases/appcast_v5.xml",
    },
    {
        "app_name": "MasergyCommunicator",
        "bundle_id": "",
        "developer": "BroadSoft",
        "input_path": "https://www.masergy.com/support-file/masergy-communicator-mac-dmg",
    },
    {
        "app_name": "Spring Tool Suite",
        "bundle_id": "org.springsource.sts.ide",
        "developer": "Pivotal",
        "input_path": "https://spring.io/tools",
    },
    {
        "app_name": "NetSpot",
        "bundle_id": "com.etwok.netspotwifi",
        "developer": "Etwok, LLC",
        "input_path": "https://www.netspotapp.com/updates/netspot2-appcast.xml",
    },
    {
        "app_name": "WiFi Explorer",
        "bundle_id": "com.adriangranados.wifiexplorer",
        "developer": "Adrian Granados-Murillo",
        "input_path": "https://www.adriangranados.com/appcasts/wifiexplorercast.xml",
    },
    {
        "app_name": "TypeIt4Me",
        "bundle_id": "com.typeit4me.TypeIt4MeMenu",
        "developer": "Riccardo Ettore",
        "input_path": "http://ettoresoftware.com/download/TypeIt4MeAppcast.xml",
    },
    {
        "app_name": "Angry IP Scanner",
        "bundle_id": "net.azib.ipscan",
        "developer": "Anton Keks",
        "input_path": "https://github.com/angryziber/ipscan",
    },
    {
        "app_name": "Typinator",
        "bundle_id": "com.macility.typinator2",
        "developer": "Ergonis Software GmbH",
        "input_path": "http://www.ergonis.com/downloads/typinator-install.dmg",
    },
    {
        "app_name": "SCAP Workbench",
        "bundle_id": "org.open-scap.scap-workbench",
        "developer": "",
        "input_path": "https://github.com/OpenSCAP/scap-workbench",
    },
    {
        "app_name": "Process Monitor",
        "bundle_id": "com.sqwarq.Process-Monitor",
        "developer": "Philip Stokes",
        "input_path": "https://s3.amazonaws.com/sqwarq.com/AppCasts/procmon-updates.xml",
    },
    {
        "app_name": "HyperDither",
        "bundle_id": "com.tinrocket.hyperdither",
        "developer": "",
        "input_path": "https://dl.dropboxusercontent.com/u/27496801/Tinrocket.com/HyperDither/HyperDither%20by%20Tinrocket.zip?dl=1",
    },
    {
        "app_name": "Solstice",
        "bundle_id": "com.mersive.solstice.client",
        "developer": "Solstice",
        "input_path": "https://www.mersive.com/download/",
    },
    {
        "app_name": "Shiori",
        "bundle_id": "com.aki-null.Shiori",
        "developer": "Akihiro Noguchi",
        "input_path": "https://aki-null.net/shiori/appcast.xml",
    },
    {
        "app_name": "Silverback",
        "bundle_id": "uk.co.clearleft.SilverbackMac",
        "developer": "Clearleft Ltd.",
        "input_path": "https://dl.devmate.com/uk.co.clearleft.SilverbackMac/Silverback.zip",
    },
    {
        "app_name": "Mountain Duck",
        "bundle_id": "io.mountainduck",
        "developer": "David Kocher",
        "input_path": "https://version.mountainduck.io/changelog.rss",
    },
    {
        "app_name": "Manuscripts",
        "bundle_id": "com.manuscripts.Manuscripts",
        "developer": "Manuscripts.app Limited",
        "input_path": "https://updates.manuscriptsapp.com/apps/manuscripts/beta/appcast.xml",
    },
    {
        "app_name": "Loopback",
        "bundle_id": "com.rogueamoeba.Loopback",
        "developer": "Rogue Amoeba Software, Inc.",
        "input_path": "https://rogueamoeba.com/loopback/download/Loopback.zip",
    },
    {
        "app_name": "Hammerspoon",
        "bundle_id": "org.hammerspoon.Hammerspoon",
        "developer": "Chris jones",
        "input_path": "https://raw.githubusercontent.com/Hammerspoon/hammerspoon/master/appcast.xml",
    },
    {
        "app_name": "KeepingYouAwake",
        "bundle_id": "info.marcel-dierkes.KeepingYouAwake",
        "developer": "Marcel Dierkes",
        "input_path": "https://newmarcel.github.io/KeepingYouAwake/appcast.xml",
    },
    {
        "app_name": "uTorrent",
        "bundle_id": "com.bittorrent.uTorrent",
        "developer": "BitTorrent, Inc",
        "input_path": "http://download.ap.bittorrent.com/track/stable/endpoint/utmac/os/osx",
    },
    {
        "app_name": "Kitematic",
        "bundle_id": "com.electron.kitematic",
        "developer": "Docker",
        "input_path": "https://github.com/docker/kitematic",
    },
    {
        "app_name": "Webex Teams",
        "bundle_id": "Cisco-Systems.Spark",
        "developer": "Webex Teams",
        "input_path": "http://www.webex.com/downloads/WebexTeams.dmg",
    },
    {
        "app_name": "Tomahawk",
        "bundle_id": "org.tomahawk-player.Tomahawk",
        "developer": "Tomahawk",
        "input_path": "http://download.tomahawk-player.org/sparkle/update.php",
    },
    {
        "app_name": "AdobeLogCollectorTool",
        "bundle_id": "com.Adobe.Installers.AdobeLogCollectorTool",
        "developer": "AdobeLogCollectorTool",
        "input_path": "http://download.adobe.com/pub/adobe/SupportTools/LogCollector/mac/LogCollectorTool.dmg",
    },
    {
        "app_name": "Ring",
        "bundle_id": "com.ring.mac",
        "developer": "Bot Home Automation",
        "input_path": "https://ring-mac-app-assets.s3.amazonaws.com/production/ring-appcast.xml",
    },
    {
        "app_name": "AdobeCreativeCloudCleanerTool",
        "bundle_id": "com.Adobe.Installers.AdobeCreativeCloudCleanerTool",
        "developer": "AdobeCreativeCloudCleanerTool",
        "input_path": "https://download.adobe.com/pub/adobe/SupportTools/Cleaner/mac/AdobeCreativeCloudCleanerTool.dmg",
    },
    {
        "app_name": "FramerX",
        "bundle_id": "com.framer.x",
        "developer": "Framer BV",
        "input_path": "https://dl.devmate.com/com.framer.x/FramerX.zip",
    },
    {
        "app_name": "Principle",
        "bundle_id": "com.danielhooper.principle",
        "developer": "Daniel Hooper",
        "input_path": "http://principleformac.com/update2.xml",
    },
    {
        "app_name": "iOSConsole",
        "bundle_id": "com.lemonjar.iosconsole",
        "developer": "Lemonjar",
        "input_path": "https://updates.lemonjar.com/iosconsole.xml",
    },
    {
        "app_name": "Aerial",
        "bundle_id": "com.JohnCoates.Aerial",
        "developer": "John Coates",
        "input_path": "https://github.com/JohnCoates/Aerial",
    },
    {
        "app_name": "ParseHub",
        "bundle_id": "org.mozilla.parsehub",
        "developer": "ParseHub",
        "input_path": "https://www.parsehub.com/static/client/parsehub.dmg",
    },
    {
        "app_name": "Amazon Drive",
        "bundle_id": "com.amazon.clouddrive.mac",
        "developer": "Amazon Drive",
        "input_path": "https://d29x207vrinatv.cloudfront.net/mac/AmazonDriveApp.zip",
    },
    {
        "app_name": "Quitter",
        "bundle_id": "com.marcoarment.quitter",
        "developer": "Full City, LLC",
        "input_path": "https://marco.org/appcasts/quitter.xml",
    },
    {
        "app_name": "Pathology",
        "bundle_id": "com.celestialteapot.direct.Pathology",
        "developer": "Todd Ditchendorf",
        "input_path": "http://celestialteapot.com/pathology/appcast/pathology.rss",
    },
    {
        "app_name": "Xmplify",
        "bundle_id": "au.com.moso.Xmplify",
        "developer": "MOSO Corporation",
        "input_path": "http://xmplifyapp.com/appcast.xml",
    },
    {
        "app_name": "Pathological",
        "bundle_id": "com.celestialteapot.Pathological",
        "developer": "Todd Ditchendorf",
        "input_path": "http://celestialteapot.com/pathological/appcast/pathological.rss",
    },
    {
        "app_name": "GoogleAppEngineLauncher",
        "bundle_id": "com.google.GoogleAppEngineLauncher",
        "developer": "Google",
        "input_path": "https://storage.googleapis.com/appengine-sdks/featured/GoogleAppEngineLauncher-",
    },
    {
        "app_name": "iCloud Control",
        "bundle_id": "com.robbertbrandsma.iCloudControl",
        "developer": "Robbert Brandsma",
        "input_path": "https://github.com/Obbut/iCloud-Control",
    },
    {
        "app_name": "YakYak",
        "bundle_id": "com.github.yakyak",
        "developer": "",
        "input_path": "https://github.com/yakyak/yakyak",
    },
    {
        "app_name": "Paw",
        "bundle_id": "com.luckymarmot.Paw",
        "developer": "Micha Mazaheri",
        "input_path": "https://luckymarmot.com/paw/download",
    },
    {
        "app_name": "WakeOnMac",
        "bundle_id": "com.doogul.WakeOnMac",
        "developer": "Doug Brown",
        "input_path": "https://software.doogul.com/wom/wom.dmg",
    },
    {
        "app_name": "TileMill",
        "bundle_id": "com.mapbox.tilemill",
        "developer": "Development Seed",
        "input_path": "https://tilemill-project.github.io/tilemill/",
    },
    {
        "app_name": "Dropzone 3",
        "bundle_id": "com.aptonic.Dropzone3",
        "developer": "Aptonic Limited",
        "input_path": "https://aptonic.com/sparkle/updates.xml",
    },
    {
        "app_name": "BlueJeans",
        "bundle_id": "com.bluejeansnet.Blue",
        "developer": "BlueJeans",
        "input_path": "https://swdl.bluejeans.com/desktop-app/mac/ga.appcast.xml",
    },
    {
        "app_name": "Hermes",
        "bundle_id": "com.alexcrichton.Hermes",
        "developer": "",
        "input_path": "https://hermesapp.org/versions.xml",
    },
    {
        "app_name": "Findings",
        "bundle_id": "com.findings.Findings",
        "developer": "Findings Software",
        "input_path": "http://downloads.findingsapp.com/appcast.xml",
    },
]
